openapi: 3.0.3

info:
  contact: {}
  description: This API is used to manage identity providers.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Identity Provider Management API
  version: "1.0"

servers:
  - url: https://{host}:{port}
    variables:
      host:
        default: "localhost"
      port:
        default: "8090"

paths:
  /identity-providers:
    get:
      description: Retrieve a list of all identity providers.
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/model.IdentityProvider'
        "400":
          description: 'Bad Request: The request body is malformed or contains invalid data.'
          content:
            application/json:
              schema:
                type: string
        "500":
          description: 'Internal Server Error: An unexpected error occurred while processing the request.'
          content:
            application/json:
              schema:
                type: string
      summary: List identity providers
      tags:
      - identity-providers
    post:
      description: Creates a new identity provider with the provided details.
      requestBody:
        description: Identity provider data
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/model.IdentityProvider'
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/model.IdentityProvider'
        "400":
          description: 'Bad Request: The request body is malformed or contains invalid data.'
          content:
            application/json:
              schema:
                type: string
        "500":
          description: 'Internal Server Error: An unexpected error occurred while processing the request.'
          content:
            application/json:
              schema:
                type: string
      summary: Create an identity provider
      tags:
      - identity-providers
  /identity-providers/{id}:
    get:
      description: Retrieve a specific identity provider using its ID.
      parameters:
      - name: id
        in: path
        description: Identity provider ID
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/model.IdentityProvider'
        "400":
          description: 'Bad Request: The request body is malformed or contains invalid data.'
          content:
            application/json:
              schema:
                type: string
        "404":
          description: 'Not Found: The identity provider with the specified ID does not exist.'
          content:
            application/json:
              schema:
                type: string
        "500":
          description: 'Internal Server Error: An unexpected error occurred while processing the request.'
          content:
            application/json:
              schema:
                type: string
      summary: Get an identity provider by ID
      tags:
      - identity-providers
    put:
      description: Update the details of an existing identity provider.
      parameters:
      - name: id
        in: path
        description: Identity provider ID
        required: true
        schema:
          type: string
      requestBody:
        description: Updated identity provider data
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/model.IdentityProvider'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/model.IdentityProvider'
        "400":
          description: 'Bad Request: The request body is malformed or contains invalid data.'
          content:
            application/json:
              schema:
                type: string
        "404":
          description: 'Not Found: The identity provider with the specified ID does not exist.'
          content:
            application/json:
              schema:
                type: string
        "500":
          description: 'Internal Server Error: An unexpected error occurred while processing the request.'
          content:
            application/json:
              schema:
                type: string
      summary: Update an identity provider
      tags:
      - identity-providers
    delete:
      description: Delete an identity provider using its ID.
      parameters:
      - name: id
        in: path
        description: Identity provider ID
        required: true
        schema:
          type: string
      responses:
        "204":
          description: No Content
        "400":
          description: 'Bad Request: The request body is malformed or contains invalid data.'
          content:
            application/json:
              schema:
                type: string
        "404":
          description: 'Not Found: The identity provider with the specified ID does not exist.'
          content:
            application/json:
              schema:
                type: string
        "500":
          description: 'Internal Server Error: An unexpected error occurred while processing the request.'
          content:
            application/json:
              schema:
                type: string
      summary: Delete an identity provider
      tags:
      - identity-providers

components:
  schemas:
    model.IdentityProvider:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        properties:
          type: array
          items:
            $ref: '#/components/schemas/model.IDPProperty'
    model.IDPProperty:
      type: object
      properties:
        name:
          type: string
        value:
          type: string
        is_secret:
          type: boolean
